### ISSUE TITLE
PHP 5.5.9

### ISSUE THREAD

**Issue by luceos** [laraflock/dashboard#1]
[laravel](http://laravel.com/docs/5.1#installation) requires php 5.5.9; travis by default uses the latest patch versions available: http://docs.travis-ci.com/user/languages/php/

Therefor you need to also include php 5.5.9 in your .travis.yml.

**Comment by iolson** [comment]
Fixed with [commit](https://github.com/laraflock/dashboard/commit/3809fe341f37f176623a45e690a889c8429dad90).
