### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by TarikAmine** [laraflock/dashboard#10]
Hi, thank you for this awesome package,
my only setback is that language is hardcoded in view files, is using localization planned in future version or is it gonna be English only?

**Comment by iolson** [comment]
@TarikAmine yes, this is in my roadmap. I will tag this as an enhancement and get to it when I have time, if you wanted to do a pull request, we can do it that way as well :)

**Comment by iolson** [comment]
I've started on the localization support on the master branch, once I get everything covered, I will merge it into 3.0

**Comment by iolson** [comment]
Fixed in v3.1.0, if I missed anything send a PR please.
