### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by luceos** [laraflock/dashboard#4]
You have the package version hardcoded in your config, it's currently set at 2.0 even for the latest 3.0 release. It might be wise not to use any hardcoded version..

For the future we might consider a generic package that informs a webmaster regularly about available updates to (any) package, there is some service that does that already..

**Comment by iolson** [comment]
That's not really meant for the actual package. That's meant for someone to put a version of their own application in the footer of the dashboard. I'll probably just update this to 1.0 or something like that and make better documentation regarding it.

**Comment by iolson** [comment]
Updated in 3.0.2 release.

**Comment by luceos** [comment]
Ah didn't know that. Must have missed it in the configuration file.
