### ISSUE TITLE
[Proposal] Ability for custom authentication method

### ISSUE THREAD

**Issue by phroggyy** [laraflock/dashboard#5]
Currently, _Dashboard_ is bound to use Sentinel. However, this turns out to be very unpractical if you only think about the admin module _after_ implementing the rest of the system. Then, you likely already have authentication in place, and using Sentinel can become a major annoyance. Hence, I propose to let the user define a custom admin authentication closure, in order to allow flexibility (keeping Sentinel, for example, as a default).

One solution is to place this within a configuration file, as below (example for using Laravel default auth):

``` php
return [
    'auth' => function() {
        return Auth::check();
    }
];
```

However, fetching from a config file might be slow, so another option is to allow the user to define this in a service provider (such as the `AppServiceProvider`) through something like the following

``` php
app('dashboard')->setAuthenticationMethod(function() {
    return \Auth::check();
});
```

**Comment by iolson** [comment]
Phroggyy, this is the reason why I let you bind a different repository to the authentication interface via the config. This will allow you to use any Auth system you would like, as long as it follows the interface, as those are used throughout the controllers.

**Comment by phroggyy** [comment]
@iolson ugh, completely missed that looking through the docs!
